import type {
  CharacterData,
  StatDefinition,
} from "./types";

export const SCHEMA_VERSION = 2;

export const statDefinitions: StatDefinition[] = [
  {
    id: "mangrit",
    name: "Mangrit",
    category: "Physical",
    description: "Strength and physical power.",
    uses: ["Feats of strength", "Physical attacks", "Explicit Mangrit damage"],
    displayOrder: 1,
  },
  {
    id: "gel-viscosity",
    name: "Gel Viscosity",
    compactName: "Gel Visc",
    category: "Physical",
    description: "Physical durability and defense.",
    uses: ["Reduces incoming Physical Damage using its Modifier"],
    displayOrder: 2,
  },
  {
    id: "scamperway",
    name: "Scamperway",
    category: "Physical",
    description: "Speed and quickness.",
    uses: ["Initiative", "Maximum AP", "Absconding", "Movement checks"],
    displayOrder: 3,
  },
  {
    id: "flummoxie",
    name: "Flummoxie",
    category: "Special",
    description: "Supernatural power and magical proficiency.",
    uses: ["Special attacks", "Explicit Flummoxie damage", "Aspect effects"],
    displayOrder: 1,
  },
  {
    id: "moxie-muffling",
    name: "Moxie Muffling",
    category: "Special",
    description: "Resistance to supernatural force.",
    uses: ["Reduces incoming Special Damage using its Modifier"],
    displayOrder: 2,
  },
  {
    id: "semperstand",
    name: "Semperstand",
    category: "Special",
    description: "Endurance and the ability to withstand physical hardship.",
    uses: ["Guard Saves", "Physical endurance", "Physical Status resistance"],
    displayOrder: 3,
  },
  {
    id: "dexcellence",
    name: "Dexcellence",
    category: "Instinctual",
    description: "Dexterity, coordination, and precise physical control.",
    uses: ["Fine motor control", "Balance", "Sleight of hand", "Precise actions"],
    displayOrder: 1,
  },
  {
    id: "triggerance",
    name: "Triggerance",
    category: "Instinctual",
    description: "Perception, awareness, and instinctive reactions.",
    uses: ["Perception", "Awareness", "Dodge strength"],
    displayOrder: 2,
  },
  {
    id: "soulicity",
    name: "Soulicity",
    category: "Instinctual",
    description: "Spiritual integrity and resistance to SBURB-specific effects.",
    uses: ["Death Saves", "Stasis", "Silence", "Dread"],
    displayOrder: 3,
  },
  {
    id: "brainitude",
    name: "Brainitude",
    category: "Mental",
    description: "Intelligence, memory, analysis, and problem-solving.",
    uses: ["Research", "Investigation", "Memory", "Resisting Confuse"],
    displayOrder: 1,
  },
  {
    id: "wisdomentality",
    name: "Wisdomentality",
    category: "Mental",
    description: "Judgment, intuition, and mental resilience.",
    uses: ["Judgment", "Intuition", "Mental resistance"],
    displayOrder: 2,
  },
  {
    id: "verballistamina",
    name: "Verballistamina",
    category: "Mental",
    description: "Charisma, persuasion, deception, leadership, and social influence.",
    uses: ["Persuasion", "Deception", "Leadership", "Spare attempts"],
    displayOrder: 3,
  },
];

export const seedCharacter: CharacterData = {
  schemaVersion: SCHEMA_VERSION,
  identity: {
    id: "char-mina-quill",
    campaignId: "campaign-glass-horizon",
    ownerUserId: "demo-player",
    playerName: "Avery Vale",
    characterName: "Mina Quill",
    portraitInitials: "MQ",
    level: 7,
    currentExp: 2850,
    expRequiredForNextLevel: 3600,
    className: "Seer",
    classDescription:
      "Seers expose useful paths, hidden connections, and missing information without resolving the Player’s choices for them.",
    aspectName: "Light",
    aspectDescription:
      "Light concerns fortune, attention, relevance, and consequential information.",
    landName: "Land of Lanterns and Labyrinths",
    grist: 1840,
    boondollars: 612,
    skillPoints: 3,
    notes:
      "Keeps a handwritten index of every suspicious coincidence. Definitely not superstitious.",
  },
  resources: {
    currentHealth: 32,
    baseMaximumHealth: 40,
    temporaryHealth: 8,
    currentPluck: 13,
    baseMaximumPluck: 18,
    currentAP: 2,
    doomMarks: 1,
    surge: 2,
    stagger: 1,
    shortRestsUsed: 1,
  },
  stats: [
    {
      definitionId: "mangrit",
      baseValue: 12,
      otherPersistentBonus: 0,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d6",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "gel-viscosity",
      baseValue: 17,
      otherPersistentBonus: 0,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d8",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "scamperway",
      baseValue: 22,
      otherPersistentBonus: 2,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d8",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "flummoxie",
      baseValue: 23,
      otherPersistentBonus: 1,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d10",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "moxie-muffling",
      baseValue: 15,
      otherPersistentBonus: 0,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d6",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "semperstand",
      baseValue: 16,
      otherPersistentBonus: 0,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d8",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "dexcellence",
      baseValue: 19,
      otherPersistentBonus: 0,
      temporaryModifier: 1,
      penalty: 0,
      growthFormula: "d8",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "triggerance",
      baseValue: 21,
      otherPersistentBonus: 0,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d10",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "soulicity",
      baseValue: 18,
      otherPersistentBonus: 0,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d8",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "brainitude",
      baseValue: 24,
      otherPersistentBonus: 0,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d10",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "wisdomentality",
      baseValue: 20,
      otherPersistentBonus: 1,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d8",
      manualOverrideEnabled: false,
    },
    {
      definitionId: "verballistamina",
      baseValue: 14,
      otherPersistentBonus: 0,
      temporaryModifier: 0,
      penalty: 0,
      growthFormula: "d6",
      manualOverrideEnabled: false,
    },
  ],
  customStats: [
    {
      id: "radnaturality",
      name: "Radnaturality",
      description:
        "Mina's rule-of-cool capability for especially wild, stylish, creative, dramatic, or entertaining actions.",
      value: 8,
      bonus: 8,
      modifierType: "full-value",
      growthInfo: "+1 at GM-awarded milestones",
      notes: "The GM decides when Radnaturality applies.",
      displayOrder: 1,
    },
    {
      id: "appraisal",
      name: "Appraisal",
      description: "Recognizing the significance, origin, and likely value of unusual objects.",
      value: 4,
      bonus: 4,
      modifierType: "full-value",
      linkedStandardStat: "Brainitude",
      notes: "Often paired with Brainitude Modifier.",
      displayOrder: 2,
    },
  ],
  items: [
    {
      id: "parallax-pike",
      name: "Parallax Pike",
      itemType: "Weapon",
      weaponkind: "spearkind",
      itemLevel: 7,
      rarity: "Exceptional",
      quantity: 1,
      shortDescription: "A split-tined spear that points toward two probable outcomes.",
      fullDescription:
        "The polished head hums near decisive moments. Mina records which tine catches the brighter reflection before committing to a plan.",
      equipped: true,
      consumable: false,
      remainingCharges: 2,
      maximumCharges: 2,
      statBonuses: [
        { statDefinitionId: "flummoxie", amount: 2 },
        { statDefinitionId: "scamperway", amount: 1 },
      ],
      majorAffixes: [
        {
          id: "forked-timeline",
          name: "Forked Timeline",
          rank: "Rank II",
          shortSummary: "Spend a charge to keep a second interpretation in play.",
          rulesText:
            "After Mina commits to a Pike Move, she may spend a charge and present an alternate reading of its outcome. The table resolves the exact benefit manually.",
          timing: "After declaring a Pike Move",
          usageLimit: "2 charges",
          maximumCharges: 2,
          currentCharges: 2,
          recoveryType: "Long Rest",
          displayOrder: 1,
        },
      ],
      minorAffixes: [
        {
          id: "bright-edge",
          name: "Bright Edge",
          shortSummary: "+2 Flummoxie while equipped.",
          rulesText: "The pike's persistent equipment bonus is included in Total Flummoxie.",
          displayOrder: 1,
        },
      ],
      refinements: ["Balanced haft", "Lantern-glass inlay"],
      curses: ["The left tine points accusingly at nearby unopened doors."],
      specialRules: ["Weapon Move selection never spends AP automatically."],
      weaponMoves: [
        {
          id: "lancing-query",
          name: "Lancing Query",
          apCost: 1,
          hitChance: "Hit 8+",
          comboChance: "Combo 15+",
          damageText: "1d8 + Mangrit Physical",
          damageType: "Physical",
          targetText: "One target in reach",
          rollText: "Roll using the table's normal weapon procedure.",
          onHitText: "Deal the listed Physical Damage.",
          onComboText: "Ask the GM one immediate tactical question about the target.",
          onCritText: "Resolve the table's normal Crit procedure.",
          effectText:
            "A direct probing thrust. This entry is a rules reference only; it does not roll, choose a target, or resolve damage.",
          displayOrder: 1,
        },
        {
          id: "borrowed-tomorrow",
          name: "Borrowed Tomorrow",
          apCost: 2,
          healthCost: 6,
          hitChance: "Hit 7+",
          comboChance: "Combo 14+",
          damageText: "2d8 Special",
          damageType: "Special",
          targetText: "One visible target",
          rollText: "Resolve the attack manually.",
          onHitText: "The target is struck by a possibility that has not happened yet.",
          durationText: "Table ruling",
          effectText:
            "Pay 6 HP to force an aggressive future into the present. The app may apply only the listed HP cost.",
          displayOrder: 2,
        },
        {
          id: "prism-break",
          name: "Prism Break",
          apCost: 2,
          pluckCost: 5,
          hitChance: "Hit 9+",
          comboChance: "Combo 16+",
          damageText: "1d10 + Flummoxie Special",
          damageType: "Special",
          targetText: "Up to two targets described by the Player",
          rollText: "Resolve all rolls and targets manually.",
          onComboText: "The Player may describe a useful beam split; the GM rules on it.",
          effectText:
            "Refract a likely outcome into two paths. The app may apply only the listed Pluck cost.",
          displayOrder: 3,
        },
      ],
      icon: "WP",
    },
    {
      id: "circuit-weave-mantle",
      name: "Circuit-Weave Mantle",
      itemType: "Armor",
      slot: "Chest Armor",
      itemLevel: 6,
      rarity: "Rare",
      quantity: 1,
      shortDescription: "A long coat stitched with pale conductive thread.",
      fullDescription:
        "Its lining flashes with diagrammatic routes whenever Mina braces for impact.",
      equipped: true,
      consumable: false,
      statBonuses: [
        { statDefinitionId: "gel-viscosity", amount: 5 },
        { statDefinitionId: "semperstand", amount: 2 },
      ],
      maximumHealthBonus: 5,
      majorAffixes: [],
      minorAffixes: [
        {
          id: "reactive-mesh",
          name: "Reactive Mesh",
          shortSummary: "+5 Gel Viscosity while equipped.",
          rulesText: "The woven lining contributes its listed persistent Stat bonus.",
          displayOrder: 1,
        },
        {
          id: "clear-channel",
          name: "Clear Channel",
          shortSummary: "+2 Semperstand while equipped.",
          rulesText: "The coat steadies Mina against physical hardship.",
          displayOrder: 2,
        },
      ],
      passiveEffects: ["Maximum Health +5 while equipped."],
      icon: "AR",
    },
    {
      id: "lucky-lens",
      name: "Lucky Lens",
      itemType: "Trinket",
      slot: "Trinket",
      itemLevel: 5,
      rarity: "Fabled",
      quantity: 1,
      shortDescription: "A brass monocle that highlights improbably useful details.",
      fullDescription:
        "The lens refuses to focus on anything ordinary. It is very smug about this.",
      equipped: true,
      consumable: false,
      statBonuses: [{ statDefinitionId: "triggerance", amount: 3 }],
      maximumPluckBonus: 2,
      remainingCharges: 1,
      maximumCharges: 1,
      majorAffixes: [
        {
          id: "find-the-thread",
          name: "Find the Thread",
          rank: "Rank I",
          shortSummary: "Spend its charge to spotlight one useful coincidence.",
          rulesText:
            "Describe the coincidence Mina is searching for. The GM determines what, if anything, the Lens reveals.",
          timing: "Exploration or Strife, when examining the scene",
          usageLimit: "1 charge",
          maximumCharges: 1,
          currentCharges: 1,
          recoveryType: "Short Rest",
          displayOrder: 1,
        },
      ],
      minorAffixes: [],
      passiveEffects: ["Maximum Pluck +2 while equipped."],
      icon: "TR",
    },
    {
      id: "perfect-attendance",
      name: "Perfect Attendance",
      itemType: "Badge",
      slot: "Badge 1",
      rarity: "Uncommon",
      quantity: 1,
      shortDescription: "Once per session, note that Mina was already here.",
      fullDescription:
        "A badge earned for arriving before the event that caused it. Resolve its narrative permission with the GM.",
      equipped: true,
      consumable: false,
      statBonuses: [],
      majorAffixes: [],
      minorAffixes: [],
      icon: "PA",
    },
    {
      id: "lamp-lighter",
      name: "Lamp-Lighter",
      itemType: "Badge",
      slot: "Badge 2",
      rarity: "Rare",
      quantity: 1,
      shortDescription: "A reminder that every labyrinth has a readable edge.",
      fullDescription:
        "Awarded after illuminating the western maze. Its full campaign meaning remains a table reference.",
      equipped: true,
      consumable: false,
      statBonuses: [{ statDefinitionId: "wisdomentality", amount: 1 }],
      majorAffixes: [],
      minorAffixes: [],
      icon: "LL",
    },
    {
      id: "red-string",
      name: "Red String Enthusiast",
      itemType: "Badge",
      slot: "Badge 3",
      rarity: "Common",
      quantity: 1,
      shortDescription: "The theory board was right eventually.",
      fullDescription:
        "A cheerful badge with far too many arrows. It has no automatic effect.",
      equipped: false,
      consumable: false,
      statBonuses: [],
      majorAffixes: [],
      minorAffixes: [],
      icon: "RS",
    },
    {
      id: "bandage-cache",
      name: "Bandage Cache",
      itemType: "Consumable",
      itemLevel: 2,
      rarity: "Common",
      quantity: 3,
      shortDescription: "Restore 8 Health. Does not restore Temporary Health.",
      fullDescription:
        "A compact roll of gel-treated bandages with very clear pictograms.",
      equipped: false,
      consumable: true,
      apCost: 1,
      healingAmount: 8,
      statBonuses: [],
      majorAffixes: [],
      minorAffixes: [],
      icon: "HP",
    },
    {
      id: "bottled-serendipity",
      name: "Bottled Serendipity",
      itemType: "Consumable",
      itemLevel: 4,
      rarity: "Uncommon",
      quantity: 2,
      shortDescription: "Restore 6 Pluck.",
      fullDescription:
        "A fizzy gold drink whose label always recommends exactly the flavor Mina wanted.",
      equipped: false,
      consumable: true,
      apCost: 1,
      pluckRestorationAmount: 6,
      statBonuses: [],
      majorAffixes: [],
      minorAffixes: [],
      icon: "PL",
    },
    {
      id: "gel-capsule",
      name: "Gel Capsule",
      itemType: "Utility Item",
      itemLevel: 3,
      rarity: "Uncommon",
      quantity: 2,
      shortDescription: "Gain 5 Temporary Health.",
      fullDescription:
        "Twist both ends and slap the capsule against armor to release a protective gel layer.",
      equipped: false,
      consumable: true,
      apCost: 1,
      temporaryHealthAmount: 5,
      statBonuses: [],
      majorAffixes: [],
      minorAffixes: [
        {
          id: "quick-set",
          name: "Quick-Set",
          shortSummary: "The gel hardens immediately.",
          rulesText: "Add the listed Temporary Health after confirmation.",
          displayOrder: 1,
        },
        {
          id: "citrus-scent",
          name: "Citrus Scent",
          shortSummary: "Smells improbably refreshing.",
          rulesText: "Informational only.",
          displayOrder: 2,
        },
      ],
      icon: "TH",
    },
    {
      id: "oracle-chalk",
      name: "Oracle Chalk",
      itemType: "Utility Item",
      itemLevel: 5,
      rarity: "Rare",
      quantity: 1,
      shortDescription: "Mark a surface with a question the maze can answer.",
      fullDescription:
        "The chalk writes in a bright line that remains visible through fog and dramatic lighting.",
      equipped: false,
      consumable: false,
      pluckCost: 2,
      remainingCharges: 3,
      maximumCharges: 3,
      statBonuses: [],
      majorAffixes: [
        {
          id: "answering-line",
          name: "Answering Line",
          rank: "Rank I",
          shortSummary: "The mark bends toward a useful route.",
          rulesText:
            "Spend one charge and 2 Pluck, then ask the GM how the maze responds.",
          pluckCost: 2,
          maximumCharges: 3,
          currentCharges: 3,
          recoveryType: "Long Rest",
          displayOrder: 1,
        },
      ],
      minorAffixes: [],
      icon: "UT",
    },
    {
      id: "sun-thread-spool",
      name: "Sun-Thread Spool",
      itemType: "Catalyst",
      rarity: "Rare",
      quantity: 4,
      shortDescription: "A warm alchemical catalyst reserved for GM-directed crafting.",
      fullDescription:
        "The prototype records this catalyst but does not generate alchemy results.",
      equipped: false,
      consumable: false,
      statBonuses: [],
      majorAffixes: [],
      minorAffixes: [],
      icon: "CA",
    },
    {
      id: "western-key",
      name: "Key of the Western Index",
      itemType: "Quest Item",
      rarity: "Unique",
      quantity: 1,
      shortDescription: "Opens a door the map insists does not exist.",
      fullDescription:
        "A quest object tracked for reference only. Quest automation is out of scope.",
      equipped: false,
      consumable: false,
      statBonuses: [],
      majorAffixes: [],
      minorAffixes: [],
      icon: "QI",
    },
  ],
  classpectEntries: [
    {
      id: "chart-the-course",
      entryType: "Class Skill",
      category: "Active",
      name: "Chart the Course",
      apCost: 1,
      pluckCost: 3,
      timing: "On Mina's turn",
      target: "Mina and willing allies who can hear her",
      effect: "Describe the safest visible path through the immediate problem.",
      duration: "Until the situation materially changes",
      shortSummary: "Spend 3 Pluck to identify a promising course.",
      fullDescription:
        "Mina names the evidence she is following and the destination she expects. Apply only the Pluck cost here; the GM resolves the information and any benefit.",
      unlocked: true,
      displayOrder: 1,
      explorationCompatible: true,
    },
    {
      id: "known-unknowns",
      entryType: "Class Skill",
      category: "Passive",
      name: "Known Unknowns",
      effect: "Mina keeps track of missing information and contradictions.",
      shortSummary: "Passive reminder for gaps in the current theory.",
      fullDescription:
        "This card does not activate or modify Stats automatically. Use it as a reminder when the table agrees a missing fact is significant.",
      unlocked: true,
      displayOrder: 2,
      explorationCompatible: true,
    },
    {
      id: "intercede",
      entryType: "Class Skill",
      category: "Reaction",
      name: "Intercede",
      apCost: 1,
      healthCost: 4,
      timing: "Reaction, when an ally follows a dangerously incomplete plan",
      condition: "The Player can explain the overlooked detail",
      effect: "Interrupt with a corrective warning; the GM resolves the outcome.",
      usageLimit: "Once per Short Rest",
      maximumCharges: 1,
      currentCharges: 1,
      recoveryType: "Short Rest",
      shortSummary: "Pay 4 HP to interrupt with a crucial correction.",
      fullDescription:
        "The app may apply the listed HP cost and mark the use. It does not validate the trigger or resolve the reaction.",
      unlocked: true,
      displayOrder: 3,
      explorationCompatible: true,
    },
    {
      id: "faultless-premise",
      entryType: "Class Skill",
      category: "Augment",
      name: "Faultless Premise",
      apCost: 1,
      timing: "When declaring another Seer Skill",
      effect: "Attach one explicit assumption to the Skill's prediction.",
      usageLimit: "2 charges per Long Rest",
      maximumCharges: 2,
      currentCharges: 1,
      recoveryType: "Long Rest",
      shortSummary: "Augment a prediction by stating its key assumption.",
      fullDescription:
        "Record the assumption in Player notes. Any mechanical consequence remains a GM ruling.",
      unlocked: true,
      displayOrder: 4,
      explorationCompatible: true,
    },
    {
      id: "lights-favor",
      entryType: "Aspect Ability",
      category: "Active",
      name: "Light's Favor",
      apCost: 2,
      pluckCost: 5,
      timing: "On Mina's turn",
      target: "One described action or object",
      effect: "Spotlight an especially fortunate interpretation.",
      duration: "One immediate resolution",
      shortSummary: "Spend 5 Pluck to spotlight a fortunate possibility.",
      fullDescription:
        "Apply only the Pluck cost in the app. Dice, targets, timing, and the exact benefit are resolved manually.",
      unlocked: true,
      displayOrder: 1,
      explorationCompatible: true,
    },
    {
      id: "beacon-in-static",
      entryType: "Aspect Ability",
      category: "Passive",
      name: "Beacon in the Static",
      effect: "Mina naturally notices conspicuous clues in chaotic scenes.",
      shortSummary: "Passive Light reminder; no automatic Stat change.",
      fullDescription:
        "The GM decides when a clue is conspicuous. This entry never reveals hidden information on its own.",
      unlocked: true,
      displayOrder: 2,
      explorationCompatible: true,
    },
    {
      id: "luck-reversal",
      entryType: "Aspect Ability",
      category: "Reaction",
      name: "Luck Reversal",
      apCost: 1,
      pluckCost: 4,
      timing: "Reaction after a conspicuously unlucky result",
      effect: "Propose how the bad result creates a new opening.",
      usageLimit: "Once per Long Rest",
      maximumCharges: 1,
      currentCharges: 1,
      recoveryType: "Long Rest",
      shortSummary: "Pay 4 Pluck to turn bad luck into an opening.",
      fullDescription:
        "The app can apply the cost and mark the use. The GM decides whether the proposed opening exists.",
      unlocked: true,
      displayOrder: 3,
      explorationCompatible: true,
    },
    {
      id: "radiant-annotation",
      entryType: "Aspect Ability",
      category: "Augment",
      name: "Radiant Annotation",
      healthCost: 3,
      timing: "When Mina explains an observed pattern",
      effect: "Make the pattern visibly obvious to allies for the scene.",
      duration: "Scene",
      shortSummary: "Pay 3 HP to make an observed pattern impossible to miss.",
      fullDescription:
        "Apply only the listed HP cost. The table determines who perceives the pattern and what that changes.",
      unlocked: true,
      displayOrder: 4,
      explorationCompatible: true,
    },
  ],
  statuses: [
    {
      id: "status-burn",
      statusName: "Burn",
      potency: "d4",
      remainingDuration: 3,
      durationType: "turns",
      saveStat: "Semperstand",
      saveDC: 12,
      source: "Lantern Wyrm",
      notes: "Reference only; do not apply damage automatically.",
    },
    {
      id: "status-silence",
      statusName: "Silence",
      remainingDuration: 1,
      durationType: "turn",
      saveStat: "Soulicity",
      saveDC: 13,
      source: "Hushed Hall",
    },
    {
      id: "status-stasis",
      statusName: "Stasis",
      source: "Negative Pluck warning",
      notes: "Awaiting GM ruling.",
    },
  ],
  turnNotes: "Ask whether the northwest mirror still reflects the boss's weak side.",
  guardState: "None",
};
